ros1_bridge/__init__.py
Since all ROS 2 code uses Python 3 and the ROS 1 packages are only available in Python 2 this needs some weird way to include `catkin_pkg` and `rospkg`.
=> allow the bridge to find Python 2 packages from ROS 1

include/ros1_bridge/factory.hpp
Required for the presentation today.
=> use sensor profile since messages might be large which is not implemented in all rmw impl for reliable qos

CMakeLists.txt
Before http://ci.ros2.org/view/packaging/job/ros2_packaging_osx/17/
After http://ci.ros2.org/view/packaging/job/ros2_packaging_osx/19/
=> ignore unused-parameter warning in ROS 1 message headers

src/simple_bridge.cpp, src/simple_bridge_1_to_2.cpp
Packaging jobs (because the CI jobs don't build the bridge):
* http://ci.ros2.org/view/packaging/job/packaging_osx/25
* http://ci.ros2.org/view/packaging/job/packaging_linux/49
Windows doesn't build the bridge, so this change has no effect there.
=> fix build of bridge for namespace change

ros1_bridge/__init__.py
This fixes the packaging jobs which were broken since https://github.com/ros2/rclpy/pull/5#issuecomment-205508263
Before:
* http://ci.ros2.org/view/packaging/job/packaging_linux/199/
* http://ci.ros2.org/view/packaging/job/packaging_osx/177/
After:
* http://ci.ros2.org/view/packaging/job/packaging_linux/200/
* http://ci.ros2.org/view/packaging/job/packaging_osx/178/
=> workaround for Python search order

README.md
e.g. `rqt` can have the topics specified through command line now, so 'shell D' is not necessary in the image demo (I left the naming of shell E the same because of the screenshot)
=> Update readme for xenial+kinetic

CMakeLists.txt, README.md, include/ros1_bridge/bridge.hpp, resource/get_mappings.cpp.em, resource/pkg_factories.cpp.em, ros1_bridge/__init__.py, src/dynamic_bridge.cpp
without this, getting a topic to be bridged requires starting up temporary subscribers on the other side. introspection tools e.g. `rostopic list` can't see ROS 2 publishers, and tools such as `rosbag record --all` aren't very usable.
With this, bridges will be made for any topic that has a known mapping, whether subscribers are on the other side or not.
right now it is trying to make a bridge for a topic even if it doesn't have a known mapping, so you get e.g. `failed to create 1to2 bridge for topic 'rosout_agg' with ROS 1 type 'rosgraph_msgs/Log' and ROS 2 type '': No template specialization for the pair` printed out. I will fix it by adding a function that check if a factory exists for the type before forcibly creating the mapping.
=> Add option for bridging all topics

ros1_bridge/__init__.py
Follow up of https://github.com/ros2/ci/pull/3. Fixes the import order failures that appeared in the last packaging job.
Before:
http://ci.ros2.org/view/packaging/job/packaging_linux/567/testReport/
After:
http://ci.ros2.org/view/packaging/job/packaging_linux/568/testReport/
=> fix import order

include/ros1_bridge/bridge.hpp, resource/get_mappings.cpp.em, src/dynamic_bridge.cpp
For example:
```
% dynamic_bridge --print-pairs
Supported ROS 2 <=> ROS 1 message type conversion pairs:
- 'diagnostic_msgs/DiagnosticArray' (ROS 2) <=> 'diagnostic_msgs/DiagnosticArray' (ROS 1)
- 'diagnostic_msgs/DiagnosticStatus' (ROS 2) <=> 'diagnostic_msgs/DiagnosticStatus' (ROS 1)
- 'diagnostic_msgs/KeyValue' (ROS 2) <=> 'diagnostic_msgs/KeyValue' (ROS 1)
- 'geometry_msgs/Point' (ROS 2) <=> 'geometry_msgs/Point' (ROS 1)
- 'geometry_msgs/Point32' (ROS 2) <=> 'geometry_msgs/Point32' (ROS 1)
- 'geometry_msgs/PointStamped' (ROS 2) <=> 'geometry_msgs/PointStamped' (ROS 1)
- 'geometry_msgs/Polygon' (ROS 2) <=> 'geometry_msgs/Polygon' (ROS 1)
- 'geometry_msgs/PolygonStamped' (ROS 2) <=> 'geometry_msgs/PolygonStamped' (ROS 1)
- 'geometry_msgs/Pose' (ROS 2) <=> 'geometry_msgs/Pose' (ROS 1)
- …
```
=> add option to dynamic_bridge to print out message type pairs

src/dynamic_bridge.cpp
Based on #65.
This at least prevents a crash due to using the invalid iterators.
=> check for substrings before using their iterator

ros1_bridge/__init__.py
[`is_field_mapping` is a function that returns a boolean](https://github.com/ros2/ros1_bridge/blob/deda687277a6dc97d87159a0dfbbee6b715d4b5f/ros1_bridge/__init__.py#L357), not a boolean itself.
same for `is_message_mapping`, but that wasn't causing me errors in my use case.
=> Call is_*_mapping functions instead of treating them as booleans

CMakeLists.txt, src/parameter_bridge.cpp
This variation of the bridge allows the user to configure a list of topics with their types and queue sizes on the ROS 1 parameter server and bridge exactly that set of topics.
[![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_packaging_linux&build=9)](http://ci.ros2.org/job/ci_packaging_linux/10/)
=> add parameter-based bridge

src/dynamic_bridge.cpp, test/test_dynamic_bridge.py.in
This just removes code that was inplace to adapt ros 1 topics and services that have leading `/` to ros 2 topics and services which did not, until recently.
This should fix https://github.com/ros2/build_cop/issues/28.
This should also remove the need to use `--bridge-all-topics`, @Karsten1987 @Kukanani fyi.
---
I also fixed an issue where the dynamic bridge would crash if the header info for a service was incomplete. The case was being caught and a message was being printed to stderr, but later the code would crash because there was a partially filled out entry in the map. So I just remove it when this case happens now. That prevents the crash, but I don't know why the service info is incomplete in these cases.
Packaging job:
[![Build …
=> Fix topic matching

src/dynamic_bridge.cpp, test/test_ros1_client.cpp
I refactored the bridge to adapt to the new api. I also just updated it to give up if the ROS 2 side has topics with different types, for example:
```
% dynamic_bridge
warning: ignoring topic '/chatter', which has more than one type: [std_msgs/Int32, std_msgs/String]
```
Connects to ros2/ros2#361
=> handle multiple types per topic

CMakeLists.txt, package.xml, test/test_dynamic_bridge.py.in
Depends on ros2/ros2cli#12.
Fixes ros2/build_cop#34.
[![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_packaging_linux&build=23)](http://ci.ros2.org/job/ci_packaging_linux/23/)
=> use rosrun API to determine talker/listener path

src/dynamic_bridge.cpp
I tested this by doing a `ulimit -n 100` and then running the bridge. It's past 7000 msgs without the "out of file descriptors" message showing up, so I think this solves it. I was kind of surprised that the `ros::TransportTCP` destructor didn't close the socket.
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=2832)](http://ci.ros2.org/job/ci_linux/2832/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=336)](http://ci.ros2.org/job/ci_linux-aarch64/336/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=2288)](http://ci.ros2.org/job/ci_osx/2288/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=2968)](http://ci.ros2.org/job/ci_windows/2968/)
=> Fix fd leak

package.xml
python3-yaml is definitely needed at build time, if the ros1_bridge_generate_factories binary is something that is installed and run by end users the exec_depend should stay as well.
```
15:49:40 make[2]: Entering directory '/tmp/binarydeb/ros-r2b2-ros1-bridge-0.0.0/obj-x86_64-linux-gnu'
15:49:40 /usr/bin/cmake -H/tmp/binarydeb/ros-r2b2-ros1-bridge-0.0.0 -B/tmp/binarydeb/ros-r2b2-ros1-bridge-0.0.0/obj-x86_64-linux-gnu --check-build-system CMakeFiles/Makefile.cmake 0
15:49:40 /usr/bin/cmake -E cmake_progress_start /tmp/binarydeb/ros-r2b2-ros1-bridge-0.0.0/obj-x86_64-linux-gnu/CMakeFiles /tmp/binarydeb/ros-r2b2-ros1-bridge-0.0.0/obj-x86_64-linux-gnu/CMakeFiles/progress.marks
15:49:40 make -f CMakeFiles/Makefile2 all
15:49:40 make[3]: Entering directory …
```
=> The python yaml module is needed for ros1_bridge_generate_factories

src/dynamic_bridge.cpp
This was introduced with the original implementation in #36.
A non C++ client might not even set these header fields. Since the bridge doesn't even use them anywhere this patch removes them (which gets rid of the repeated warning).
This PR together with #90 should resolve #64.
=> remove check for header fields request_type and response_type

include/ros1_bridge/factory.hpp, package.xml
The patch at least reduces the amount of printed lines (related to #64).
=> only show a message for passing the message of a specific type pair once

test/test_ros2_client.cpp
4s is not always enough, e.g.:
http://ci.ros2.org/view/packaging/job/packaging_linux-aarch64/195/testReport/junit/(root)/test_dynamic_bridge__rmw_fastrtps_cpp_RelWithDebInfo/test_dynamic_bridge_srv_1to2/:
```
(test_dynamic_bridge_srv_1to2__dynamic_bridge) pid 43970: ['/opt/ros/kinetic/env.sh', '/home/rosbuild/ci_scripts/ws/build/ros1_bridge/dynamic_bridge'] (stderr > stdout, all > console)
(test_dynamic_bridge_srv_1to2__ros1server) pid 43973: ['/opt/ros/kinetic/env.sh', '/home/rosbuild/ci_scripts/ws/build/ros1_bridge/test_ros1_server'] (stderr > stdout, all > console)
(test_dynamic_bridge_srv_1to2__ros2client) pid 43981: ['/home/rosbuild/ci_scripts/ws/build/ros1_bridge/test_ros2_client_cpp'] (stderr > stdout, all > console)
[test_dynamic_bridge_srv_1to2__ros1server] ?[31m[ERROR] …
```
=> Increase timeout waiting for server for ros2 client in tests

cmake/find_ros1_package.cmake
The comment in the code mostly explains it, but because of changes
to upstream catkin/roscpp, we need to expand the types of things
we look at for linking.  With this patch, building against
roscpp kinetic 1.12.7 and 1.12.12 works.
fixes ros2/build_cop#68
Signed-off-by: Chris Lalancette <clalancette@osrfoundation.org>
=> Fix building of ros1_bridge against newer roscpp.

CMakeLists.txt
This is needed to support cmake 3.10. We could define the policy based on the version of CMake but I preferred updating the codebase to have something compliant with all cmake versions without relying on undefined behavior.
More details at https://cmake.org/cmake/help/git-stage/policy/CMP0070.html
Example of CMake warning without this patch:
```
Policy CMP0070 is not set: Define file(GENERATE) behavior for relative
paths.  Run "cmake --help-policy CMP0070" for policy details.  Use the
cmake_policy command to set the policy and suppress this warning.
file(GENERATE) given relative OUTPUT path:
test/test_services__rmw_connext_cpp_RelWithDebInfo.py
This is not defined behavior unless CMP0070 is set to NEW.  For
compatibility with older versions of CMake, the previous undefined behavior
will …
```
=> cmake 3.10 compatibility: pass absolute path to file(GENERATE) function

ros1_bridge/__init__.py
This at least catches the case where the mapping rule file doesn't even contain a list.
Based on https://answers.ros.org/question/286315/problem-with-ros1-bridge-bridging-a-custom-mesage/
=> add an error message if the mapping rules are not a list

CMakeLists.txt, include/ros1_bridge/builtin_interfaces_factories.hpp, include/ros1_bridge/convert_builtin_interfaces.hpp, package.xml, resource/get_factory.cpp.em, ros1_bridge/__init__.py, src/builtin_interfaces_factories.cpp, src/convert_builtin_interfaces.cpp
Only slightly related to ros2/ros1_bridge#104.
While the bridge can already handle fields with a `Duration` or `Time` type it currently can't map the messages `std_msgs/Duration|Time` with `builtin_interfaces/Duration|Time`.
With this patch the following appears when invoking the dynamic bridge with `--print-pairs`:
```
- 'builtin_interfaces/Duration' (ROS 2) <=> 'std_msgs/Duration' (ROS 1)
- 'builtin_interfaces/Time' (ROS 2) <=> 'std_msgs/Time' (ROS 1)
```
And the following example works:
* ROS 1 side:
```
rostopic pub /time std_msgs/Time "data:
secs: 1 
nsecs: 2"
```
* ROS 2 side:
```ros2 topic echo /time builtin_interfaces/Time```
=> Map duration and time messages

include/ros1_bridge/builtin_interfaces_factories.hpp, src/builtin_interfaces_factories.cpp
followup of https://github.com/ros2/ros1_bridge/pull/106
example failures: [![Build Status](https://ci.ros2.org/buildStatus/icon?job=packaging_linux&build=1027)](https://ci.ros2.org/view/packaging/job/packaging_linux/1027/)
CI: [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_packaging_linux&build=71)](https://ci.ros2.org/job/ci_packaging_linux/71/)
The ros1 headers have to come first to avoid "Found C system header after other header. Should be: builtin_interfaces_factories.h, c system, c++ system, other."
Then I tried to keep ros1 and ros2 message includes together, then the others. I know there's a strange mix of system headers, it's what was needed to make the linters pass. If you prefer a different combination please commit directly after making sure it passes the linters …
=> Fix linter failures from includes

include/ros1_bridge/bridge.hpp, include/ros1_bridge/factory.hpp, include/ros1_bridge/factory_interface.hpp
Issue mentioned in #43 and #111, solution based on discussion in #43. Branched from ardent as I am not able to build master on my system.
Tested by using parameter_bridge and multiple ROS1 and ROS2 publishers and subscribers on the same topic.
Thank you @wjwwood for your help!
This PR is copy of broken PR #112. Sorry for the inconvenience.
=> Duplicate messages in bidirectional_bridge fix

package.xml, ros1_bridge/__init__.py
Follow-up of https://github.com/ament/ament_package/pull/75: `ament_package` doesnt provide `parse_package` anymore.
I also simplified the import of `catkin_pkg` as we now enforce the presence of the Python3 version of `catkin_pkg`.
CI will be ran after the nightlies. Placing this in review in the meantime
=> use catkin_pkg to parse packages

cmake/find_ros1_package.cmake
`pkg_check_modules()` simply output the following not helpful error message when a requested module is not found:
> A required package was not found
Therefore this patch handles printing the error message separately to include the module name.
=> include module name which wasn't found in error message

include/ros1_bridge/bridge.hpp, resource/get_mappings.cpp.em, ros1_bridge/__init__.py, src/dynamic_bridge.cpp
=> print service pairs as well

CMakeLists.txt
When building this package using 
`colcon build`
No message is displayed if the ros1 libraries are not found, due to the `STATUS` logger level of these CMake messages. 
Changing the logger level to `WARNING` solves the problem.
=> Changed cmake message logger level

ros1_bridge/__init__.py
Handle `.idl` files generated by ros2/rosidl#331 properly.
=> handle idl files correctly

CMakeLists.txt, include/ros1_bridge/factory.hpp, include/ros1_bridge/factory_interface.hpp
In order to leverage the bridge to convert ros messages from ros1 to ros2, we would like to expose this function. This allows us to convert messages without using pub/sub.
cc @botteroa-si
=> expose convert function

include/ros1_bridge/factory.hpp, include/ros1_bridge/factory_interface.hpp
This allows specifying a custom QoS profile for ROS2 components, or setting a `latch` flag on the created ROS1 publisher.
=> Allow custom QoS settings for pub/sub factories

CMakeLists.txt
Related to #168.
This patch improves the error behavior is the ROS 2 package `diagnostic_msgs` isn't available. Without the patch `diagnostic_msgs` is found from ROS 1 (since in ROS 2 it wasn't available) and the build fails with missing headers / symbols.
=> ensure that the diagnostic_msgs package is from ROS 2

CMakeLists.txt, cmake/find_ros1_package.cmake, package.xml
Signed-off-by: Karsten Knese <karsten@openrobotics.org>
I believe this is the correct fix for exporting the `find_ros1_package.cmake. This allows other packages to use this macro straight after finding the `ros1_bridge` package.
see: https://github.com/ros2/rosbag2/pull/90#discussion_r256232380
please advise how to test this patch. Also I would appreciate if this could be backported to crystal.
=> export find_ros1_package cmake

CMakeLists.txt
Follow up of #169.
This ensures that after finding the wrong `diagnostic_msgs` package consecutive configure runs will retry to find the package in a potentially updated environment.
=> invalidate wrong cached result for diagnostic_msgs

include/ros1_bridge/factory.hpp, include/ros1_bridge/factory_interface.hpp, src/bridge.cpp
Switch to rclcpp logging and improve messages (Close #166)
=> Switch to rclcpp logging and improve messages

CMakeLists.txt, cmake/find_ros1_package.cmake, package.xml
This allows other packages to use macros to find ros1 packages straight after finding the `ros1_bridge` package.
see: ros2/rosbag2#90 (comment)
=> [backport] export find_ros1_package cmake extras

src/dynamic_bridge.cpp
Signed-off-by: Gonzalo de Pedro <gonzalo@depedro.com.ar>
This changes the order of initialization of nodes. By initializing firs the ROS2 node it allows cmd args to be passed to it.
=> Allows propagations of cmd args to rclcpp::init

ros1_bridge/__init__.py
Similar to https://github.com/colcon/colcon-metadata/pull/14
Note: I didnt get a chance to test the change, but ROS2 CI should cover the parsing of the mapping rules
=> use yaml.safe_load instead of deprecated yaml.load

include/ros1_bridge/factory.hpp
Fixes #181 which is a regression of #167.
[![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_packaging_linux&build=184)](https://ci.ros2.org/job/ci_packaging_linux/184/)
=> fix log messages

CMakeLists.txt, README.md, resource/interface_factories.cpp.em, resource/pkg_factories.cpp.em, resource/pkg_factories.hpp.em, ros1_bridge/__init__.py
In short: the PR trades a longer build time for a lower memory consumption during the build :balance_scale:
Resolves ros2/build_cop#106.
Before the patch the generated code produced one `.cpp` file per package. The memory consumption of the compiler therefore scales with the number of messages per package and the template specialization stuff is not light on memory. For packages like `geometry_msgs`, `sensor_msgs` or `std_msgs` which each contain ~30 messages the memory consumption of a single compilation unit could easily reach 2.5 GB. Building the bridge with N threads where N is by default the number of CPU cores could therefore easily exhaust the available memory.
With the patch the generated code produces one `.cpp` file per interface file (message, service). Therefore the memory …
=> Interface specific compilation units

ros1_bridge/__init__.py
https://github.com/ros2/rosidl/pull/359 removed the backwards
compatibility import of rosidl_adapter.parse from rosidl_parser,
so instead we just directly import rosidl_adapter.parse and
use it as necessary.
Signed-off-by: Chris Lalancette <clalancette@openrobotics.org>
=> Fix the generator.

README.md
1.  Remove language about release-alpha8; that is ancient history
2.  Remove language talking about ROS 1 on Windows, since that is a
thing now
3.  Change the language about sourcing ROS 1 before building the whole
workspace; while we still don't want people to do it, the reasoning was
outdated.
Signed-off-by: Chris Lalancette <clalancette@openrobotics.org>
=> Some small fixes to the README

include/ros1_bridge/factory.hpp, src/simple_bridge.cpp, src/simple_bridge_1_to_2.cpp, src/simple_bridge_2_to_1.cpp
=> changes to avoid deprecated API's

include/ros1_bridge/factory.hpp, src/simple_bridge.cpp
Follow up of #189 to make the build pass again.
[![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_packaging_linux&build=201)](https://ci.ros2.org/job/ci_packaging_linux/201/)
=> fix build by passing options

resource/interface_factories.cpp.em
Fixes https://github.com/ros2/build_cop/issues/192. This pull request fixes ros1 bridge mapping factory template to take into account the interface type in the message type name. 
* CI packaging Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_packaging_linux&build=200)](http://ci.ros2.org/job/ci_packaging_linux/200/)
* Packaging Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=packaging_linux&build=1459)](http://ci.ros2.org/job/packaging_linux/1459/)
Another one to be added to the list in https://github.com/ros2/ros2/issues/677.
=> Adds interface type to ROS2 message type name

resource/get_mappings.cpp.em, resource/interface_factories.cpp.em
Follow up after 816b667de32f6a5ab45a7cfc22b931f3d2ac1749, introduced by #191. Prefixes (i.e. `msg`, `srv`) were still missing in a few other places.
* CI packaging Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_packaging_linux&build=205)](http://ci.ros2.org/job/ci_packaging_linux/205/)
I managed to reproduce latest test failures on https://github.com/ros2/build_cop/issues/192 locally and all appear to be fixed by this patch.
=> Use interface kind names properly in ROS2 interface type names.

test/test_services_across_dynamic_bridge.py.in
=> Handle launch_testing assertExitCodes correctly

CMakeLists.txt, src/dynamic_bridge.cpp
Closes https://github.com/ros2/build_cop/issues/192, by disabling rosout logging whenever the RMW implementation of choice is based on Fast-RTPS.
Additionally, some typos I found in the CMakeLists.txt affecting the tests (!) and got past review/CI before are fixed in their own separate commit.
=> Disable rosout logging for the bridge

package.xml
Used here: https://github.com/ros2/ros1_bridge/blob/dad409c681ea78d2d7107e64ccac8e03842c23e3/test/test_dynamic_bridge.py.in#L21
Addresses the bridge related test failures: http://build.ros2.org/view/Cci/job/Cci__nightly_ubuntu_bionic_amd64/200/testReport/
=> add missing test dependency in Crystal

README.md
Adding a clarification in documentation, because @clalancette and I think `rostopic echo` is an obvious first thing that everyone starting to use the bridge would try, that there should be solid documentation so that people have the correct expectation that they need an actual subscriber, not just `echo` and decide the bridge doesn't work for them, which we saw happen.
=> Add note in documentation about rostopic echo

src/parameter_bridge.cpp
I have set ros1 type to "" since in create_bidirectional_bridge it can find out which type to use for ros1 when only specifying ros2 type.
An alternative fix would be to allow to specify different type for ros1 and ros2 in the parameters.
=> Fix parameter bridge for topic if ros1 and ros2 type have a different name

src/dynamic_bridge.cpp
One more brick in the wall of https://github.com/ros2/ros2/issues/721
Fixes warnings seen here https://ci.ros2.org/job/ci_packaging_linux-armhf/4/warnings23Result/package.1964502061/
=> Use %zu print format for size_t

src/static_bridge.cpp
Fixes #208.
No reason to trigger CI for this change since the `static_bridge` isn't covered by any test.
=> fix typename in static bridge

README.md
Related to #205. I also found the instructions unclear about which ROS versions one has to source to run the bridge, so the proposal is to make it clearer.
=> Clearer instructions for example ros1->ros2

src/dynamic_bridge.cpp
Closes https://github.com/ros2/build_cop/issues/229. Precisely what the title says. Our workaround (https://github.com/ros2/ros1_bridge/pull/197) for https://github.com/ros2/rmw_fastrtps/issues/265 got outdated after https://github.com/ros2/rcl/pull/477. I also took the opportunity to simplify the code a bit.
CI packaging Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_packaging_linux&build=265)](http://ci.ros2.org/job/ci_packaging_linux/265/)
=> Update __log_rosout_disable workaround to use --ros-args.

doc/index.rst, src/dynamic_bridge.cpp
This pull requests adapts `ros1_bridge` to the changes introduced by https://github.com/ros2/rcl/pull/495.
=> Promote special CLI rules to flags.

test/test_services_across_dynamic_bridge.py.in, test/test_topics_across_dynamic_bridge.py.in
Removing some of the 'magic' features from launch_testing that we want to deprecate.
For background, see ros2/launch#346
Signed-off-by: Pete Baughman <pete.baughman@apex.ai>
=> Don't use launch_testing features that will be deprecated

src/builtin_interfaces_factories.cpp
Based on https://answers.ros.org/question/335602/ros1_bridge-for-builtin-interfaces-results-in-an-error/
=> fix bridging builtin_interfaces Duration and Time

ros1_bridge/__init__.py
Based on this bug report: https://answers.ros.org/question/340860/ros1_bridge-fails-to-generate-service-when-custom-message-from-the-same-package-is-used/
Packaging build: [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_packaging_linux&build=281)](https://ci.ros2.org/job/ci_packaging_linux/281/) (unrelated warnings: ros2/rclcpp#962)
=> fix service with custom mapped message field

src/dynamic_bridge.cpp, src/parameter_bridge.cpp
Style update to match the ROS 2 development guide and pass with the updated linter configuration from ament/ament_lint#210.
Before: [![Build Status](https://ci.ros2.org/buildStatus/icon?job=packaging_linux&build=1747)](https://ci.ros2.org/view/packaging/job/packaging_linux/1747/) (7 test failures)
After: [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_packaging_linux&build=289)](https://ci.ros2.org/job/ci_packaging_linux/289/) (3 remaining / unrelated test failures)
=> code style only: wrap after open parenthesis if not in one line

src/dynamic_bridge.cpp
Precisely what the title says. To be tested and merged along with https://github.com/ros2/rmw_fastrtps/pull/342.
=> Drop workaround for Fast-RTPS typesupport issue 

CMakeLists.txt
Fixes https://github.com/ros2/build_farmer/issues/267
Depends on https://github.com/ament/ament_cmake/pull/223
Note, this change will ignore *all* deprecation warnings produced by calling `find_package(actionlib_msgs)`. I'm not sure of a nice way in CMake to ignore a single message coming from a command, but I think this solution is reasonable since I don't expect other deprecation warnings to come from finding `actionlib_msgs`. Alternatively, we could introduce a new variable in `ament_cmake` to toggle the deprecation warning, e.g. `actionlib_msgs_IGNORE_DEPRECATED`, but it doesn't seem very elegant.
=> Ignore actionlib_msgs deprecation warnings

test/test_topics_across_dynamic_bridge.py.in
As logs go out `stdout` and not `stderr` in ROS 1. 
This pull request fixes recent nightly packaging jobs' test failures.
* Packaging Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_packaging_linux&build=302)](http://ci.ros2.org/job/ci_packaging_linux/302/)
=> Assert ROS 1 nodes' stdout.

include/ros1_bridge/factory.hpp
Another follow up of https://github.com/ros2/rclcpp/pull/1047.
=> updates since changes to message_info in rclcpp

src/simple_bridge.cpp
Fixes #262.
As already done in the [simple_bridge_1_to_2](https://github.com/ros2/ros1_bridge/blob/37a06eb64c97571766e245b6b2784a99c1c4df69/src/simple_bridge_1_to_2.cpp#L52). Otherwise subscribes must use best effort and can't use reliable.
=> use reliable publisher in simple bridge

include/ros1_bridge/factory.hpp
A ROS 1 publisher can be invalid if multiple publishers are created with different latching attributes. If such a publisher is encounters just log a warning instead of exiting.
(The publisher is intentionally not removed since it would be added shortly after again.)
Packaging build with only FastRTPS: [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_packaging_linux&build=358)](https://ci.ros2.org/job/ci_packaging_linux/358/)
=> gracefully handle invalid ROS 1 publishers

src/dynamic_bridge.cpp
Fixes #265. Requires ros2/rclcpp#1131.
CI builds testing `rclcpp` with only FastRTPS:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=10872)](http://ci.ros2.org/job/ci_linux/10872/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=6235)](http://ci.ros2.org/job/ci_linux-aarch64/6235/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=8856)](http://ci.ros2.org/job/ci_osx/8856/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=10765)](http://ci.ros2.org/job/ci_windows/10765/)
Packaging build with only FastRTPS: [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_packaging_linux&build=359)](https://ci.ros2.org/job/ci_packaging_linux/359/)
=> fix removing obsolete ROS 2 service bridges

src/parameter_bridge.cpp
Replaces #249.
CI packaging build: [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_packaging_linux&build=354)](https://ci.ros2.org/job/ci_packaging_linux/354/)
=> deprecate package key for service parameters, use full type instead

ros1_bridge/__init__.py
Fixes issue #257
Recreation of PR #259 to do master->master
=> When generating service mappings cast pair to set to avoid duplicate pairs

ros1_bridge/__init__.py
Fixes the problem reported in https://answers.ros.org/question/354302/ros1_bridge-build-error-for-turtlebot3/
CI build just to check for regressions: [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_packaging_linux&build=371)](https://ci.ros2.org/job/ci_packaging_linux/371/)
=> fix multiple definition if message with same name as service exists

README.md
Motivated by this question: https://answers.ros.org/question/358103/ros-1-bridge-requires-the-topic-to-be-published-both-sides/
=> document explicitly passing the topic type to 'ros2 topic echo'

include/ros1_bridge/bridge.hpp, include/ros1_bridge/factory.hpp, include/ros1_bridge/factory_interface.hpp, src/bridge.cpp, src/dynamic_bridge.cpp
Otherwise the latched ROS 1 message won't be "latched" on the ROS 2 side and commonly ROS 2 subscribers of the `/tf_static` topic will use the QoS `transient_local` and therefore won't be matched with `volatile` publishers.
[![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_packaging_linux&build=415)](https://ci.ros2.org/job/ci_packaging_linux/415/)
=> use hardcoded QoS (keep all, transient local) for /tf_static topic in dynamic_bridge

CMakeLists.txt, resource/interface_factories.cpp.em, ros1_bridge/__init__.py
This pull request updates the `ros1_bridge` to use the `.idl` file versions of messages rather than `.msg` versions, switching to use `rosidl_parser` rather than `rosidl_adapter` respectively.
This also allows the bridge to work with messages that are defined as only `.idl` files (lacking a `.msg` version) as well, so long as the messages follow the conventional `(<package_name>, msg, <message_name>)` triplet.
The changes include:
- changing the python scripts used to generate code for the bridge to prefer `.idl` files over `.msg` and to call into `rosidl_parser` rather than `rosidl_adapter`
- update the template files to use the objects returned from `rosidl_parser`, which differ from `rosdil_adapter`
- this matches the changes made to most of the type support packages when `.idl` file …
=> update to use rosidl_parser and .idl files rather than rosidl_adapter and .msg files

CMakeLists.txt, resource/interface_factories.cpp.em, ros1_bridge/__init__.py
This is forward porting a change from Dashing made in https://github.com/ros2/ros1_bridge/pull/292 into master.
CI:
- `ci_packaging_linux`: [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_packaging_linux&build=431)](https://ci.ros2.org/job/ci_packaging_linux/431/)
Once this one is merged, I'll backport it to Foxy and Eloquent.
closes https://github.com/ros2/ros1_bridge/issues/187
=> [forward port] update to use rosidl_parser and .idl files rather than rosidl_adapter and .msg files

resource/interface_factories.cpp.em
This patch fixes a bug where the `sizeof` calls used to compare sizes of fixed sized arrays/sequences were faulty when elements of the arrays have different memory layouts.
We've tested it against the Apex use case that was failing to compile. It's ready for review, and then I'll work on backports.
=> fix bug with sizeof when type of the arrays differ

src/parameter_bridge.cpp
as the documentation for parameter bridge is lacking, better to have comments without typo to avoid time waste on the user side
=> very minor typo in comments

src/bridge.cpp
This has caused failures in the nightly jobs on platforms where ros1_bridge is built.
I believe that it is related to this PR: https://github.com/ros2/rclcpp/pull/1442
@audrow Can you confirm that this was an expected side effect?
=> Fix logging for updated rclcpp interface

ros1_bridge/__init__.py
This fixes compilation issues on systems with Python versions older than 3.6 by removing f-Strings.  https://github.com/ros2/ros1_bridge/issues/305
=> remove f-strings for dashing support

src/dynamic_bridge.cpp
https://github.com/ros2/rcutils/pull/340 deprecates `rcutils/get_env.h`. This PR doesn't need to wait until the `rcutils` PR is merged, though.
I simply removed the `#include` since nothing from that header was actually used.
=> Remove unused header

CMakeLists.txt, package.xml
This makes `ros1_bridge` use `FindPython3`, and makes the dependency on Python 3 explicit
Related to ros2/python_cmake_module#6
Blocks ament/ament_cmake#355
=> Use FindPython3 and make Python dependency explicit

package.xml, src/dynamic_bridge.cpp
See https://github.com/ros2/rclcpp/pull/1727#issuecomment-901241040
Signed-off-by: Christophe Bedard <bedard.christophe@gmail.com>
=> Use rcpputils/scope_exit.hpp instead of rclcpp/scope_exit.hpp

include/ros1_bridge/builtin_interfaces_factories.hpp
This should fix the linter errors on the rolling jobs:
https://ci.ros2.org/view/packaging/job/packaging_linux/2525/
https://ci.ros2.org/view/packaging/job/packaging_linux-aarch64/1877/
https://build.ros2.org/view/Rci/job/Rci__nightly-release_ubuntu_focal_amd64/569/
Signed-off-by: Jorge Perez <jjperez@ekumenlabs.com>
=> Fix cpplint error

include/ros1_bridge/factory.hpp, include/ros1_bridge/factory_interface.hpp, src/dynamic_bridge.cpp, src/parameter_bridge.cpp
By convention, service calls in ROS should have a short execution time. However, since the bridge currently doesn't yet have full support for actions, services are sometimes used where a bit of computation time is needed.
Currently the service call timeout on service_bridge_1_to_2 is hard-coded to 5 seconds for all services. This constrain is not transparent to the user, that needs to take a look at the code to understand what's going on.
The PR adds a new parameter, "service_execution_timeout", that can be set by the user to extend (or reduce) the required timeout for service calls. This was added for both the dynamic_bridge and the parameter_bridge.
=> Parametrizing service execution timeout

README.md, src/dynamic_bridge.cpp
I noticed that the README.md file had a number of minor issues that meant that it wasn't as clear as it could be.  This PR clears them up.
- I rewrapped all lines to 80 columns.  This makes it a little easier to read in a text editor.
- I added `bash` as the [info string](https://github.github.com/gfm/#info-string) of every fenced code block.  This makes Github render the blocks correctly, and makes copying simpler.
- I added two new environment variables to the prerequisites.  These are `ROS1_INSTALL_PATH`, and `ROS2_INSTALL_PATH`.  They exist to make it simple to run the scripts regardless of which versions of ROS 1 and 2 are currently in use.  Instructions on how to set them are given within the README.md
=> Cleanup of README.md

include/ros1_bridge/factory.hpp, package.xml
Also make sure to declare a direct dependency on boost.
While we are always getting it from ROS 1, this code directly
uses it and so should also declare a dependency.
Signed-off-by: Chris Lalancette <clalancette@openrobotics.org>
I recently attempted to build the ros1_bridge against the ROS (1) packages available directly in Ubuntu Jammy.  This is the only thing that prevented me from doing so, and is an obvious fix anyway.
=> Make sure to use fully-qualified boost placeholders.

CMakeLists.txt
ROS1 packages aren't available on all platforms.  In order to keep
ros1_bridge in ros2.repos without warnings turning CI yellow, we need to
suppress this warning.
This is an alternative to https://github.com/ros2/ros2/pull/1256
This will require packing CI jobs to be updated with a new cmake arg `-DROS1_PACKAGES_UNAVAILABLE=true` for Jammy jobs.
```
$ colcon build --packages-select ros1_bridge
Starting >>> ros1_bridge
--- stderr: ros1_bridge                           
CMake Warning at CMakeLists.txt:36 (message):
Failed to find ROS 1 roscpp, skipping...
---
Finished <<< ros1_bridge [2.30s]
```
vs 
```
colcon build --packages-select ros1_bridge --cmake-args -DROS1_PACKAGES_UNAVAILABLE=1
Starting >>> ros1_bridge
Finished <<< ros1_bridge [2.36s]                  
Summary: 1 package finished …
```
=> Suppress warning when packages aren't available

README.md
I have tested it.
terminal 1
<pre>
ros2 run ros1_bridge parameter_bridge
Trying to create bidirectional bridge for topic '/chatter' with ROS 2 type 'std_msgs/msg/String'
[INFO] [1651472131.323351466] [ros_bridge]: create bidirectional bridge for topic /chatter
The parameter 'services_1_to_2' either doesn't exist or isn't an array
Trying to create bridge for ROS 1 service '/add_two_ints' with type 'roscpp_tutorials/TwoInts'
Created 2 to 1 bridge for service /add_two_ints
[INFO] [1651472131.772500582] [ros_bridge]: Passing message from ROS 1 std_msgs/String to ROS 2 std_msgs/msg/String (showing msg only once per type)
</pre>
terminal 2
<pre>
$ rosrun roscpp_tutorials add_two_ints_server
[ INFO] [1651472257.007540349]: request: x=1, y=2
[ INFO] [1651472257.010445376]:   sending back …
=> to correct Examples 4

resource/interface_factories.cpp.em
As reported in #313, `ros1_bridge` can not successfully build with newer versions of GCC (such as 11.2.0 on Ubuntu Jammy).
This is one alternative which uses `std::tuple_size` on ROS 2's `std::array` (https://en.cppreference.com/w/cpp/container/array/tuple_size), and uses `static_size` from ROS 1's `boost::array` members. 
Here is an example in Compiler Explorer to demonstrate the methodology:  [example](https://godbolt.org/#z:OYLghAFBqd5TKALEBjA9gEwKYFFMCWALugE4A0BIEAZgQDbYB2AhgLbYgDkAjF%2BTXRMiAZVQtGIHgBYBQogFUAztgAKAD24AGfgCsp5eiyahUAUgBMAIUtXyKxqiIEh1ZpgDC6egFc2TEAAOcncAGQImbAA5PwAjbFIQAGYecgAHdCViFyYvX38g9MzsoXDImLZ4xJT7bEdnIREiFlIiPL8A4IdsJxymlqIy6LiE5NSlZtb2gq7JwYjhytGUgEp7dB9SVE4uSySI1F8cAGozJI8W0hYATzPcMy0AQT2Do%2BxT85cJ0mx2O4fnk8XkxDj4TmcPLF0JkiAB6S43AB0SDSaX%2BQKe3x8TmOAFlsEolCx …
=> Fix array static_assertion with newer compilers

README.md
https://github.com/ros2/ros1_bridge/issues/356 highlighted an error in the README that probably arose from the fact that the service parameter bridge is monodirectional. This PR aims to fix that by adding a clarificatory note.
Also, the comments in the example `yaml` file were updated, and some minor ROS1/2 formatting was done.
=> Clarify README (Example 4 and parameter bridge service directionality)

ros1_bridge/__init__.py
As reported in #354 bridge fails when ros2 message uses standard namespaces (std_msgs, geometry_msgs, etc.) to be mapped with  ros1 messages. Note: this works as expected when no namespaces are used on ros2 side, regardless of what's on ros1 side.
It was failing while returning package name and message name parsed from a `rosidl_parser.definition.NamespacedType` object. Type field was incorrect, seems to be using `rosidl_parser` for messages and `rosidl_adapter` for services, as far as my understanding. Updated the function description too.
=> Fixed index for ros2 namespace type messages

CMakeLists.txt, README.md, include/ros1_bridge/bridge.hpp, package.xml, src/bridge.cpp, src/parameter_bridge.cpp
Had some trouble using the `parameter_bridge` with `/tf_static` Turns out, I/m not the only one: https://answers.ros.org/question/349230/problem-passing-tf_static-through-ros1_bridge-to-ros2/ . The `dynamic_bridge` has an special case for this topic introduced in https://github.com/ros2/ros1_bridge/pull/282, but not in the `parameter_bridge`. 
To tackle that and be the most general I could be, I extended the `parameter_bridge` to set specific QoS settings per topic, allowing one the implement that special case if required. 
I've used this config for testing (also with different and illegal values for the settings):
`bridge.yaml`. 
```yaml
topics:
- 
topic: /chatter  # ROS1 topic name
type: std_msgs/msg/String  # ROS2 type name
queue_size: 1  # For the publisher back to ROS1
- 
topic: …
```
=> Parametrize Quality of Service in `parameter_bridge`. 

doc/index.rst, ros1_bridge/__init__.py
As requested by, and closes: https://github.com/ros2/ros1_bridge/issues/364
This PR implements a new `enable_foreign_mappings` mapping rule that allows one to override the package name check that forces a user to define any mapping rules that target a bridge ROS 2 package from that package itself.
This will let you define mappings from OUTSIDE a target message's package.
As in the `Known Issues` section, you'll probably need to run the bridge with `--bridge-all-topics` to get the bridge working with custom messages.
See the [docs](https://github.com/methylDragon/ros1_bridge/blob/permissive_mapping/doc/index.rst) for more details
Set the `enable_foreign_mappings` rule to `true`/`True`/1 in your custom mapping rules file!
It'll override the check for **EVERY RULE** defined in that file!
``` …
```
=> Implement Foreign Mapping Check Override

CMakeLists.txt
This PR makes the `xmlrpcpp` dependency search only occur if ROS 1 is found. This is because on a system with only ROS 2 installed, `xmlrpcpp` might not be installed, leading to the build of `ros1_bridge` failing for an unexpected (by the user) reason.
For more info, see this comment: https://github.com/ros2/ros1_bridge/pull/331#issuecomment-1188111510
=> Move xmlrpcpp find_package so it only searches if ROS 1 is found

README.md
A tiny edit of the documentation for `parameter_bridge` in `README.md`, with the purpose of correcting the `services_1_to_2` parameter name to match the source code.
https://github.com/ros2/ros1_bridge/blob/46375ff576b4d12e3037b024e86fc666d29f2a62/src/parameter_bridge.cpp#L257
=> Fix typo (`services_1_or_2` -> `services_1_to_2`)

CMakeLists.txt, include/ros1_bridge/factory.hpp, include/ros1_bridge/factory_interface.hpp, package.xml, test/test_convert_generic.cpp
This adds functions to convert between generic message types for ROS1 (ShapeShifter) and ROS2 (SerializedMessage)
This is useful for custom bag recording tools. For us specifically, there is a tool (action_monitor) that records certain topics at specific times based on the current robot action. If robot is idle, we record very few topics. If robot is navigating, we record many more topics.
We'de like to extend this tool to record both ROS1 and ROS2 topics at the same time to a ROS1 bag format.
If we just used dynamic_bridge to bridge all ROS2 topics, we'de pay heavy penalty bridging unnecessary topics when robot is idle.
To subscribe to an arbitrary ROS2 topic, rclcpp provides create_generic_subscription which invokes a callback that takes SerializedMessage. Because there is no concrete …
=> ros1_bridge function for converting generic message types

ros1_bridge/__init__.py
In `determine_field_mapping`, there was an early return inside a loop over all mapping rules. If there were any mapping rules but they don't specify *field* mappings, the early return made the function return without creating field mappings automatically.
For a particular message type, ROS 1's uuid_msgs/UniqueID vs ROS 2's unique_identifier_msgs/UUID, the message definition is exactly the same but type name is not. The only mapping rule defined for `unique_identifier_msgs/UUID` is that it maps to `uuid_msgs/UniqueID`, but no *field* mappings are needed because the definitions are the same: https://github.com/ros2/unique_identifier_msgs/blob/rolling/mapping_rules.yaml
But, then we hit the early return (because the for-loop is ran without any rule applying to the message at hand and thus …
=> Apply automatic mapping rules in case only package+message mapping exists

CMakeLists.txt, include/ros1_bridge/builtin_interfaces_factories.hpp, include/ros1_bridge/convert_builtin_interfaces.hpp, include/ros1_bridge/convert_decl.hpp, include/ros1_bridge/factory.hpp, package.xml, resource/interface_factories.cpp.em, ros1_bridge/__init__.py, src/builtin_interfaces_factories.cpp, src/convert_builtin_interfaces.cpp, test/test_ros2_to_ros1_serialization.cpp
Provide functions to potentially save some CPU when converting ROS messages by allow "direct" serialization of ROS2 message classes to ROS1 streams.
Currently, when ros1_bridge bridges a ROS2 topics to a ROS1 topics, it requires three steps
1. Deserialize ROS2 stream into a ROS2 message
2. Use convert_2_to_1 to copy members from ROS2 object to ROS1 message
3. Serialize ROS1 into ROS1 stream.
Using new feature removes a conversion step
1. Deserialize ROS2 stream into a ROS2 message
2. Serialize ROS2 into ROS1 stream.
Here's what the convert_2_to_1 function looks like geometry_msgs::Vector3
```C++
template<>
void Factory< ... >::convert_2_to_1(
const geometry_msgs::msg::Vector3 & ros2_msg,
geometry_msgs::Vector3 & ros1_msg)
{
ros1_msg.x = ros2_msg.x;
ros1_msg.y = ros2_msg.y;
ros1_msg.z = …
```
=> Provide direct serialization of ROS2 messsage to ROS1 streams

.gitignore
The current gitignore file makes it difficult to include the repository as a submodule, if working inside a larger repository. 
Improving the gitignore file will make this easier and simplify testing while contributing to the project by also reducing the likelihood of an accidental push containing editor-specific config.
=> Improved gitignore to exclude build files and similar editor-based tools

package.xml
https://github.com/ros2/ros1_bridge/pull/401 added a dependency which should not be handled by rosdep, so removing from package.xml
=> Remove xmlrpcpp from package.xml

README.md
Summary
This PR updates the README to clarify ros1_bridge compatibility with ROS and Ubuntu versions, particularly in light of ROS 1 reaching end-of-life and Ubuntu 24.04 dropping ROS 1 support.
- Changes Made    
Added a "Supported ROS and Ubuntu Versions" section with a compatibility matrix.    
Clarified that ROS 1 Noetic is the only supported ROS 1 version for Ubuntu 20.04.    
Explained that Ubuntu 24.04 does not support ROS 1, making it incompatible with ros1_bridge.    
Included supported ROS 2 distributions per Ubuntu release (including Kilted Kaiju for Ubuntu 24.04).    
Improved wording for clarity and accuracy.
- Motivation
To help users avoid compatibility issues when setting up ros1_bridge, especially with newer Ubuntu versions and unsupported ROS 1 installations.
-  Notes …
=> Adding compatibility matrix to Readme
