ros2/ros1_bridge

- CMakeLists.txt
- README.md
- cmake/find_ros1_package.cmake
As a follow up of this ticket should I prepare PRs to rename all message packages again to their original names?
> use pkg-config to find ROS 1 packages

- bin/ros1_bridge_generate_factories
- include/ros1_bridge/factory.hpp
- package.xml
- resource/generated_factories.cpp.template
- ros1_bridge/__init__.py
- src/dynamic_bridge.cpp
- src/listener.cpp
- src/simple_bridge.cpp
- src/simple_bridge_1_to_2.cpp
- src/simple_bridge_2_to_1.cpp
- src/static_bridge.cpp
- src/talker.cpp
Connects to ros2/ros1_bridge#3
> update dynamic bridge to create unidirection bridges based on runtime topic information

- CMakeLists.txt
Connects to ros2/rmw_implementation#3
> use add_executable_for_each_rmw_implementations() from rmw_implementation

- doc/index.rst
- ros1_bridge/__init__.py
See `doc/index.rst` for what it does.
> support custom mapping rules

- include/ros1_bridge/bridge.hpp
- include/ros1_bridge/factory.hpp
- include/ros1_bridge/factory_interface.hpp
- src/dynamic_bridge.cpp
- src/listener.cpp
- src/simple_bridge.cpp
- src/simple_bridge_1_to_2.cpp
- src/simple_bridge_2_to_1.cpp
- src/static_bridge.cpp
- src/talker.cpp
http://ci.ros2.org/job/ros2_batch_ci_osx/362/
> update code to pass ament_cpplint

- include/ros1_bridge/factory.hpp
Fix cpplint warning
Connects to https://github.com/ros2/ros2/issues/12
> Fix cpplint warning

- CMakeLists.txt
- package.xml
- src/dynamic_bridge.cpp
- src/simple_bridge.cpp
- src/simple_bridge_1_to_2.cpp
- src/simple_bridge_2_to_1.cpp
- src/static_bridge.cpp
Connect to ros2/rmw_implementation#9
This will make the packaging jobs pass for the typesupport refactoring branch:
* http://ci.ros2.org/view/packaging/job/packaging_linux/67/
* http://ci.ros2.org/view/packaging/job/packaging_osx/43/
* http://ci.ros2.org/view/packaging/job/packaging_windows_opensplice/55/
> use rclcpp library, use new type support

- README.md
Some things are no longer necessary.
> update from source build instructions

- resource/generated_factories.cpp.em
- ros1_bridge/__init__.py
> change .template into .em

- CMakeLists.txt
Fixes #26. Connect to #26.
Please review.
> fix link order

- ros1_bridge/__init__.py
Connects to ament/ament_index#17
> update ament_index_python API

- README.md
- doc/index.rst
- include/ros1_bridge/factory.hpp
- include/ros1_bridge/factory_interface.hpp
- package.xml
- resource/get_factory.cpp.em
- resource/pkg_factories.cpp.em
- resource/pkg_factories.hpp.em
- ros1_bridge/__init__.py
- src/dynamic_bridge.cpp
- test/test_ros1_bridge.py.in
* Removed separate file for mapping services
* Other minor changes
> Rework after the review (#36)

- README.md
> update references to rclcpp_tutorials to be demo_nodes_cpp

- README.md
- test/test_ros2_client.cpp
Addresses: https://github.com/ros2/rclcpp/pull/284#issuecomment-267793761
> Use std chrono literals

- CMakeLists.txt
Connect to ros2/rcl#106
[![Build Status](http://ci.ros2.org/buildStatus/icon?job=packaging_linux&build=541)](http://ci.ros2.org/job/packaging_linux/541/)
> use rmw implementation

- cmake/find_ros1_package.cmake
> remove unnecessary include

- src/dynamic_bridge.cpp
Before the polling lambda modified the maps while the `update_bridge` is iterating over them.
Now these changes are build up in a separate variable before the variables passed by reference to `update_bridge`. When they are swapped the global mutex is being locked.
Fixes #61.
> fix race conditions

- CMakeLists.txt
Connect to ros2/ros2#364.
Ready for review.
> install executables in package specific path

- README.md
> note about memory

- ros1_bridge/__init__.py
> implicitly inherit from object

- ros1_bridge/__init__.py
follow up of https://github.com/ros2/ci/pull/98
should fix test failures on [packaging jobs](http://ci.ros2.org/view/packaging/job/packaging_linux/lastCompletedBuild/testReport/)
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_packaging_linux&build=40)](http://ci.ros2.org/job/ci_packaging_linux/40/)
> update style to satisfy new flake8 plugins

- README.md
> add missing dependencies in readme

- src/dynamic_bridge.cpp
connects to ament/uncrustify#18
ci_packaging_linux: [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_packaging_linux&build=47)](http://ci.ros2.org/job/ci_packaging_linux/47/)
> update style to match latest uncrustify

- include/ros1_bridge/factory.hpp
- resource/pkg_factories.cpp.em
Fixes #95.
[![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_packaging_linux&build=49)](http://ci.ros2.org/job/ci_packaging_linux/49/)
> print bridged type names

- CMakeLists.txt
- package.xml
Connect to ament/ament_cmake#115.
> use ament_cmake_pytest instead of ament_cmake_nose

- package.xml
connects to ros2/common_interfaces#45
> depend on rosidl_interfaces_packages group

- README.md
> match topic name printed in console

- doc/index.rst
> clarify that all field must be listed explicitly

- test/test_dynamic_bridge.py.in
> migrate launch -> launch.legacy

- package.xml
PR opened for visibility. Fast-forwarding this commit onto master.
> Prepare 0.5.0

- ros1_bridge/__init__.py
This is now ready for review with steps to reproduce and test
Connects to #134
> rule can be a message mapping and a field_mapping

- doc/index.rst
> update doc to reflect that any mapping combination is supported

- doc/index.rst
- package.xml
- ros1_bridge/__init__.py
> Fast forward bouncy branch to current master for Bouncy patch 2 release

- include/ros1_bridge/factory.hpp
> use new error handling API from rcutils

- doc/index.rst
- ros1_bridge/__init__.py
Similar functionality as it is already possible for messages.
> support for custom field mapping for services

- ros1_bridge/__init__.py
Fixes #150.
[![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_packaging_linux&build=151)](https://ci.ros2.org/job/ci_packaging_linux/151/)
> fix is_package_mapping check

- CMakeLists.txt
- src/bridge.cpp
- src/dynamic_bridge.cpp
Expose libros1_bridge functions via headers
> Allow external use of ros1_bridge factories

- package.xml
- test/test_dynamic_bridge.py.in
> Drops legacy launch API usage.

- package.xml
> Add launch along with launch_testing as test dependencies.

- src/simple_bridge.cpp
> Corrected publish calls with shared_ptr signature

- include/ros1_bridge/bridge.hpp
- include/ros1_bridge/factory.hpp
- src/simple_bridge_1_to_2.cpp
Leftovers of https://github.com/ros2/ros1_bridge/pull/188.
> Corrected publish calls with shared_ptr signature, leftovers

- README.md
- doc/index.rst
Signed-off-by: Mabel Zhang <mabel@openrobotics.org>
Add documentation for setting up workspace and compiling custom message types and the bridge.
> Add documentation of workspace setup for custom messages

- src/parameter_bridge.cpp
Follow up of https://github.com/ros2/ros1_bridge/pull/176#discussion_r292172285
> fix cosmetic in message

- include/ros1_bridge/bridge.hpp
- resource/get_mappings.cpp.em
> fix showing duplicate keys in --print-pairs

- src/builtin_interfaces_factories.cpp
> [backport dashing] fix bridging builtin_interfaces Duration and Time

- src/builtin_interfaces_factories.cpp
Backport of #224. Redo of #229.
> [backport dashing] fix bridging builtin_interfaces Duration and Time (take 2)

- ros1_bridge/__init__.py
> [backport dashing] fix service with custom mapped message field

- test/test_ros2_client.cpp
> avoid new deprecations

- README.md
https://github.com/ros2/ros1_bridge/issues/38 has been resolved.
> Remove outdated information on Fast RTPS bug

- ros1_bridge/__init__.py
> [backport eloquent] fix multiple definition if message with same name as service exists

- ros1_bridge/__init__.py
> [backport dashing] fix multiple definition if message with same name as service exists

- resource/interface_factories.cpp.em
> fix bug with sizeof when type of the arrays differ (#298)

- CMakeLists.txt
- resource/interface_factories.cpp.em
- ros1_bridge/__init__.py
Backport of https://github.com/ros2/ros1_bridge/pull/296 and a subsequent bug fix #298.
> [backport foxy] support idl files on the ROS 2 side of the bridge

- CMakeLists.txt
- resource/interface_factories.cpp.em
- ros1_bridge/__init__.py
Backport of #296 and a subsequent bug fix #298.
> [backport eloquent] support idl files on the ROS 2 side of the bridge

- .github/workflows/main.yml
See if that fixes the apt-update part of CI
Signed-off-by: Shane Loretz <sloretz@osrfoundation.org>
> Bump ros-tooling/setup-ros@v0.2

- package.xml
> Update maintainers 🔥
